quote params

diff --git a/tools/gpio/gpio-sloppy-logic-analyzer b/tools/gpio/gpio-sloppy-logic-analyzer
--- a/tools/gpio/gpio-sloppy-logic-analyzer
+++ b/tools/gpio/gpio-sloppy-logic-analyzer
@@ -61,7 +61,7 @@ EOF
 
 set_newmask()
 {
-	for f in $(find $1 -iname "$2"); do echo $NEWMASK > $f 2>/dev/null; done
+	for f in $(find "$1" -iname "$2"); do echo "$NEWMASK" > "$f" 2>/dev/null; done
 }
 
 init_cpu()
@@ -71,7 +71,7 @@ init_cpu()
 	mount | grep -q $CPUSETDIR || mount -t cpuset cpuset $CPUSETDIR
 	[ -d $LACPUSETDIR ] || mkdir $LACPUSETDIR
 
-	echo $ISOL_CPU > $LACPUSETDIR/cpus
+	echo "$ISOL_CPU" > $LACPUSETDIR/cpus
 	echo 1 > $LACPUSETDIR/cpu_exclusive
 	echo 0 > $LACPUSETDIR/mems
 
@@ -84,9 +84,9 @@ init_cpu()
 
 	# Move tasks away from isolated CPU
 	for p in $(ps -o pid | tail -n +2); do
-		MASK=$(taskset -p $p)
+		MASK=$(taskset -p "$p")
 		[ "${MASK##*: }" != "$OLDMASK" ] && continue
-		taskset -p $NEWMASK $p
+		taskset -p "$NEWMASK" "$p"
 	done 2>/dev/null >/dev/null
 
 	echo 1 > /sys/module/rcupdate/parameters/rcu_cpu_stall_suppress
@@ -101,7 +101,7 @@ parse_triggerdat()
 			chan=${elem%[lhfrLHFR]}
 			mode=${elem#$chan}
 			# Check if we could parse something and the channel number fits
-			[ $chan != $elem ] && [ $chan -le $MAX_CHANS ] || { echo "Syntax error: $elem" && exit 1; }
+			[ "$chan" != "$elem" ] && [ "$chan" -le $MAX_CHANS ] || { echo "Syntax error: $elem" && exit 1; }
 			bit=$((1 << ($chan - 1)))
 			mask=$(($mask | $bit))
 			case $mode in
@@ -118,26 +118,26 @@ parse_triggerdat()
 
 do_capture()
 {
-	taskset $1 echo 1 > $LASYSFSDIR/capture
+	taskset "$1" echo 1 > "$LASYSFSDIR"/capture
 
 	SRTMP=$(mktemp -d)
-	echo 1 > $SRTMP/version
-	cp $LASYSFSDIR/sample_data $SRTMP/logic-1-1
-	cat > $SRTMP/metadata <<EOF
+	echo 1 > "$SRTMP"/version
+	cp "$LASYSFSDIR"/sample_data "$SRTMP"/logic-1-1
+	cat > "$SRTMP"/metadata <<EOF
 [global]
 sigrok version=0.2.0
 
 [device 1]
 capturefile=logic-1
-total probes=$(cat $LASYSFSDIR/meta_data | wc -l)
+total probes=$(cat "$LASYSFSDIR"/meta_data | wc -l)
 samplerate=${SAMPLEFREQ}Hz
 unitsize=1
 EOF
-	cat $LASYSFSDIR/meta_data >> $SRTMP/metadata
+	cat "$LASYSFSDIR"/meta_data >> "$SRTMP"/metadata
 
 	ZIPNAME="$OUTPUTDIR/${LASYSFSDIR##*/}-$(date +%s).sr"
-	zip -jq $ZIPNAME $SRTMP/*
-	rm -rf $SRTMP
+	zip -jq "$ZIPNAME" "$SRTMP"/*
+	rm -rf "$SRTMP"
 }
 
 REP=$(getopt -a -l path:,init:,sample_freq:,num_samples:,duration-us:,trigger:,output-dir:,help -o i:s:n:d:t:o:h -- "$@") || exit 1
@@ -158,32 +158,32 @@ while true; do
 done
 
 for f in $NEEDEDCMDS; do
-	command -v $f >/dev/null || { echo "Command '$f' not found"; exit 1; }
+	command -v "$f" >/dev/null || { echo "Command '$f' not found"; exit 1; }
 done
 
-[ $SAMPLEFREQ -eq 0 ] && echo "Invalid sample frequency" && exit 1
+[ "$SAMPLEFREQ" -eq 0 ] && echo "Invalid sample frequency" && exit 1
 
 [ -z "$LASYSFSDIR" ] && LASYSFSDIR="$SYSFSDIR/$(ls -1 $SYSFSDIR | head -n1)"
 [ ! -d "$LASYSFSDIR" ] && echo "LA directory '$LASYSFSDIR' not found!" && exit 1
 
-[ -n "$INITCPU" ] && init_cpu $INITCPU
+[ -n "$INITCPU" ] && init_cpu "$INITCPU"
 [ ! -d "$LACPUSETDIR" ] && echo "Auto-Isolating CPU1" && init_cpu 1
 
 NDELAY=$((1000000000 / $SAMPLEFREQ))
-NDELAY_ACQ=$(cat $LASYSFSDIR/delay_ns_acquisition)
-[ $NDELAY_ACQ -eq 0 ] && echo "Invalid acquisition delay received" && exit 1
+NDELAY_ACQ=$(cat "$LASYSFSDIR"/delay_ns_acquisition)
+[ "$NDELAY_ACQ" -eq 0 ] && echo "Invalid acquisition delay received" && exit 1
 NDELAY_USER=$(($NDELAY - $NDELAY_ACQ))
 MAXFREQ=$((1000000000 / $NDELAY_ACQ))
 
 [ $NDELAY_USER -lt 0 ] && NDELAY_USER=0 && SAMPLEFREQ=$MAXFREQ && echo "Capping sample_freq to $MAXFREQ"
-echo $NDELAY_USER > $LASYSFSDIR/delay_ns_user
+echo $NDELAY_USER > "$LASYSFSDIR"/delay_ns_user
 
 [ -n "$DURATION" ] && NUMSAMPLES=$(($SAMPLEFREQ * $DURATION / 1000000))
-echo $NUMSAMPLES > $LASYSFSDIR/buf_size
+echo $NUMSAMPLES > "$LASYSFSDIR"/buf_size
 
 if [ -n "$TRIGGERDAT" ]; then
-	parse_triggerdat $TRIGGERDAT
-	printf "$TRIGGER_BINDAT" > $LASYSFSDIR/trigger 2>/dev/null
+	parse_triggerdat "$TRIGGERDAT"
+	printf "$TRIGGER_BINDAT" > "$LASYSFSDIR"/trigger 2>/dev/null
 	[ $? -gt 0 ] && echo "Trigger data '$TRIGGERDAT' rejected" && exit 1
 fi
 
