even more error checking, script linting, and fixing 'cpumask' for taskset

diff --git a/tools/gpio/gpio-sloppy-logic-analyzer b/tools/gpio/gpio-sloppy-logic-analyzer
--- a/tools/gpio/gpio-sloppy-logic-analyzer
+++ b/tools/gpio/gpio-sloppy-logic-analyzer
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/sh -eu
 # Helper script for the Linux Kernel GPIO sloppy logic analyzer
 #
 # Copyright (C) Wolfram Sang <wsa@sang-engineering.com>
@@ -14,6 +14,7 @@ ladirname='gpio-sloppy-logic-analyzer'
 outputdir="$PWD"
 neededcmds='taskset zip'
 max_chans=8
+duration=
 initcpu=
 lasysfsdir=
 triggerdat=
@@ -68,7 +69,7 @@ fail()
 
 set_newmask()
 {
-	for f in $(find "$1" -iname "$2"); do echo "$newmask" > "$f" 2>/dev/null; done
+	for f in $(find "$1" -iname "$2"); do echo "$newmask" > "$f" 2>/dev/null || true; done
 }
 
 init_cpu()
@@ -76,15 +77,15 @@ init_cpu()
 	isol_cpu="$1"
 	[ -d $cpusetdir ] || mkdir $cpusetdir
 	mount | grep -q $cpusetdir || mount -t cpuset cpuset $cpusetdir
-	[ -d $lacpusetdir ] || mkdir $lacpusetdir
+	[ -d "$lacpusetdir" ] || mkdir "$lacpusetdir"
 
-	cur_cpu="$(cat $lacpusetdir/cpus)"
+	cur_cpu="$(cat "$lacpusetdir"/cpus)"
 	[ "$cur_cpu" = "$isol_cpu" ] && return
 	[ -n "$cur_cpu" ] && fail "CPU$isol_cpu requested but CPU$cur_cpu already isolated"
 
-	echo "$isol_cpu" > $lacpusetdir/cpus || fail "Could not isolate CPU$isol_cpu. Does it exist?"
-	echo 1 > $lacpusetdir/cpu_exclusive
-	echo 0 > $lacpusetdir/mems
+	echo "$isol_cpu" > "$lacpusetdir"/cpus || fail "Could not isolate CPU$isol_cpu. Does it exist?"
+	echo 1 > "$lacpusetdir"/cpu_exclusive
+	echo 0 > "$lacpusetdir"/mems
 
 	oldmask=$(cat /proc/irq/default_smp_affinity)
 	val=$((0x$oldmask & ~(1 << isol_cpu)))
@@ -95,9 +96,9 @@ init_cpu()
 
 	# Move tasks away from isolated CPU
 	for p in $(ps -o pid | tail -n +2); do
-		mask=$(taskset -p "$p")
+		mask=$(taskset -p "$p") || continue
 		[ "${mask##*: }" != "$oldmask" ] && continue
-		taskset -p "$newmask" "$p"
+		taskset -p "$newmask" "$p" || continue
 	done 2>/dev/null >/dev/null
 
 	echo 1 > /sys/module/rcupdate/parameters/rcu_cpu_stall_suppress
@@ -131,7 +132,7 @@ parse_triggerdat()
 
 do_capture()
 {
-	taskset "$1" echo 1 > "$lasysfsdir"/capture
+	taskset "$1" echo 1 > "$lasysfsdir"/capture || fail "Capture error"
 
 	srtmp=$(mktemp -d)
 	echo 1 > "$srtmp"/version
@@ -182,7 +183,7 @@ sysfsdir="$debugdir/$ladirname"
 
 [ -d "$sysfsdir" ] || fail "Could not find logic analyzer root dir '$sysfsdir'. Module loaded?"
 [ -x "$sysfsdir" ] || fail "Could not access logic analyzer root dir '$sysfsdir'. Need root?"
-[ -z "$lasysfsdir" ] && lasysfsdir="$(find $sysfsdir -mindepth 1 -type d -print -quit)"
+[ -z "$lasysfsdir" ] && lasysfsdir="$(find "$sysfsdir" -mindepth 1 -type d -print -quit)"
 [ -d "$lasysfsdir" ] || fail "Logic analyzer directory '$lasysfsdir' not found!"
 [ -d "$outputdir" ] || fail "Output directory '$outputdir' not found!"
 
@@ -206,7 +207,7 @@ if [ -n "$triggerdat" ]; then
 	printf "$trigger_bindat" > "$lasysfsdir"/trigger 2>/dev/null || fail "Trigger data '$triggerdat' rejected"
 fi
 
-workcpu=$(cat $lacpusetdir/effective_cpus)
+workcpu=$(cat "$lacpusetdir"/effective_cpus)
 [ -z "$workcpu" ] && fail "No isolated CPU found"
-cpumask=$((1 << workcpu))
-do_capture $cpumask &
+cpumask=$(printf '%x' $((1 << workcpu)))
+do_capture "$cpumask" &
